### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mmagnus** [mmagnus/PyMOL4Spliceosome#1]
- [ ] Mg2+ as own layer for each step
- [x] fix bug: U2 for Bact is right now unknown
- [x] add more structures, e.g., B,
- [ ] tri-snRNP
- [ ] unify naming syntax of objects in sessions
